JFLAGS = --module-path /usr/share/openjfx/lib --add-modules=javafx.base,javafx.controls,javafx.fxml,javafx.graphics,javafx.media,javafx.swing,javafx.web
JC = javac
JR = java
default: PlantFactory.class ShroomPea.class PuffShroom.class LawnMower.class GameBase.class Level.class User.class Pea.class Living.class Plants.class Shooter.class Blocker.class Bomber.class SunProvider.class SunFlower.class CherryBlaster.class PeaShooter.class Wallnut.class Zombies.class NormalZombie.class Sun.class ChooseLevelController.class SavedGamesScreenController.class InGameMenuController.class levelScreenController.class EntryScreenControllerExisting.class UsernamePageController.class LoginPageController.class EntryScreenControllerNew.class Screen3controller.class Screen2controller.class Screen1controller.class WelcomeScreenController.class Game.class

PlantFactory.class: PlantFactory.java
	@$(JC) $(JFLAGS) PlantFactory.java

ShroomPea.class: ShroomPea.java
	@$(JC) $(JFLAGS) ShroomPea.java

PuffShroom.class: PuffShroom.java
	@$(JC) $(JFLAGS) PuffShroom.java

LawnMower.class: LawnMower.java
	@$(JC) $(JFLAGS) LawnMower.java

Level.class: Level.java
	@$(JC) $(JFLAGS) Level.java

GameBase.class: GameBase.java
	@$(JC) $(JFLAGS) GameBase.java

User.class: User.java
	@$(JC) $(JFLAGS) User.java

Pea.class: Pea.java
	@$(JC) $(JFLAGS) Pea.java

Sun.class: Sun.java
	@$(JC) $(JFLAGS) Sun.java

Plants.class: Plants.java
	@$(JC) $(JFLAGS) Plants.java

Shooter.class: Shooter.java
	@$(JC) $(JFLAGS) Shooter.java

Blocker.class: Blocker.java
	@$(JC) $(JFLAGS) Blocker.java

Bomber.class: Bomber.java
	@$(JC) $(JFLAGS) Bomber.java

SunProvider.class: SunProvider.java
	@$(JC) $(JFLAGS) SunProvider.java

SunFlower.class: SunFlower.java
	@$(JC) $(JFLAGS) SunFlower.java

CherryBlaster.class: CherryBlaster.java
	@$(JC) $(JFLAGS) CherryBlaster.java

PeaShooter.class: PeaShooter.java
	@$(JC) $(JFLAGS) PeaShooter.java

Wallnut.class: Wallnut.java
	@$(JC) $(JFLAGS) Wallnut.java

NormalZombie.class : NormalZombie.java
	@$(JC) $(JFLAGS) NormalZombie.java

Zombies.class: Zombies.java
	@$(JC) $(JFLAGS) Zombies.java

SavedGamesScreenController.class: SavedGamesScreenController.java
	@$(JC) $(JFLAGS) SavedGamesScreenController.java

ChooseLevelController.class: ChooseLevelController.java
	@$(JC) $(JFLAGS) ChooseLevelController.java


Living.class: Living.java
	@$(JC) $(JFLAGS) Living.java


InGameMenuController.class: InGameMenuController.java
	@$(JC) $(JFLAGS) InGameMenuController.java

levelScreenController.class: levelScreenController.java
	@$(JC) $(JFLAGS) levelScreenController.java

EntryScreenControllerExisting.class: EntryScreenControllerExisting.java
	@$(JC) $(JFLAGS) EntryScreenControllerExisting.java

UsernamePageController.class: UsernamePageController.java
	@$(JC) $(JFLAGS) UsernamePageController.java

LoginPageController.class: LoginPageController.java
	@$(JC) $(JFLAGS) LoginPageController.java

EntryScreenControllerNew.class: EntryScreenControllerNew.java
	@$(JC) $(JFLAGS) EntryScreenControllerNew.java

Screen3controller.class: Screen3controller.java
	@$(JC) $(JFLAGS) Screen3controller.java

Screen2controller.class: Screen2controller.java
	@$(JC) $(JFLAGS) Screen2controller.java

Screen1controller.class: Screen1controller.java
	@$(JC) $(JFLAGS) Screen1controller.java

WelcomeScreenController.class: WelcomeScreenController.java
	@$(JC) $(JFLAGS) WelcomeScreenController.java

Game.class: Game.java
	@$(JC) $(JFLAGS) Game.java

run:
	@$(JR) $(JFLAGS) Game

clean:
	@rm *.class